### ISSUE TITLE
allow titles as array

### ISSUE THREAD

**Issue by wizidot** [nikopol/Harry-Plotter#7]
Hi, thanks for your code. 
I need to have different titles by bullet, and i didn't find any way to achieve that. I've find why in the code l(754) :
```php
v={
            v: b.v,
            V: smallNum(b.v),
            l: data[b.nds].lab[b.n],
            n: b.n,
            t: data[b.nds].tit,
            p: b.pct||percent(b.v,mx),
            s: mx,
            S: smallNum(mx)
         };
```
if you change just like that you can use title as array :
```php
v={
            v: b.v,
            V: smallNum(b.v),
            l: data[b.nds].lab[b.n],
            n: b.n,
            t: data[b.nds].tit[b.n]||data[b.nds].tit,
            p: b.pct||percent(b.v,mx),
            s: mx,
            S: smallNum(mx)
         };
```

Sorry for my english.
bye.

**Comment by nikopol** [comment]
hi,
could you provide me a sample usage/config to understand why are you not using labels instead ?
--
salut,
pourrais tu me fournir un exemple d'usage/configuration car je ne comprends pas pourquoi tu n'utilises pas les labels ?

**Comment by wizidot** [comment]
Hello,
J'ai besoin d'avoir  des labels numériques et des titres qui soient des dates dans les tooltips. Si j'ai une chaîne dans les titres elle sera la même de partout. Mon petit patch résout mon souci, maintenant j'ai pas testé dans d'autres configurations.

**Comment by nikopol** [comment]
the dataset title is also used to display the legend box, and can't be an array.
but, you can use a callback to setup the text you want, like this :

    harry({
       ...your parameters...
       mouseover: {
            text: function(o){ 
                // this function will be called for each lines with the following parameters :
                // {v:value, l:label, n:index, t:title, s: sum, V:abbr.value, S: abbrev.sum}
                return my_titles[o.n]+' '+o.l+' : '+o.v;
             }
       }
    });
